### ISSUE TITLE
Don't works without placeholder

### ISSUE THREAD

**Issue by Klemart3D** [anydigital/float-label-css#29]
Float label works with `placeholder=""` but it don't works without placeholder attribute in an input element.

I found a workaround by styling an invisible placeholder if it is equal to `#` (like to disable `href="#"` links), by adding this code in `input, select, textarea { } selector` :

``` css
&[placeholder="#"]::placeholder {
    color:transparent;
}
```
